//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPharmacies
    {
        public int ProductID { get; set; }
        public int PharmacyID { get; set; }
        public int Count { get; set; }
    
        public virtual Pharmacies Pharmacies { get; set; }
        public virtual Products Products { get; set; }
    }
}
