//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificallyProducts
    {
        public int ID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int ProductsID { get; set; }
        public int PharmaciesID { get; set; }
        public Nullable<int> OnlineOrderID { get; set; }
        public bool InStock { get; set; }
    
        public virtual OnlineOrder OnlineOrder { get; set; }
        public virtual Products Products { get; set; }
    }
}
