//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplies()
        {
            this.ProductsSupply = new HashSet<ProductsSupply>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public decimal Price { get; set; }
        public int StoragesID { get; set; }
        public int PharmaciesID { get; set; }
    
        public virtual Pharmacies Pharmacies { get; set; }
        public virtual Storages Storages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsSupply> ProductsSupply { get; set; }
        public virtual Users Users { get; set; }
    }
}
